
stages:
  - packageInstall
  - testPackage
  - failPackage
  - successPackage
  - userAdd
  - testUserAdd
  - failUserAdd
  - successUserAdd

# bloc packageInstall

packageInstall:
  stage: packageInstall
  script:
    - cd /builds/sicreji/deploiementlocal/scripts
    - echo "Execution du script ... "
    - ./admin.sh package nano >> filetest
  artifacts:
    paths:
      - /usr/local/bin/nano
      - /builds/sicreji/deploiementlocal/scripts

testPackage:
  stage: testPackage

  script:
    - cd /builds/sicreji/deploiementlocal/scripts
    - test -s filetest

  when: on_success


failPackage:
  stage: failPackage
  script:
    - echo "Echec du test d'installation d'un package"
  when: on_failure

successPackage:
  stage: successPackage
  script:
    - echo "Réussite du test d'installation d'un package"
  when: on_success

# bloc userAdd

userAdd:
  stage: userAdd
  script:
    - cd /builds/sicreji/deploiementlocal/scripts
    - echo "Execution du script ... "
    - ./admin.sh userAdd toto
    - cat /etc/passwd | grep toto >> testUser

  artifacts:
    paths:
      - /builds/sicreji/deploiementlocal/scripts

testUserAdd:
  stage: testUserAdd

  script:
    - cd /builds/sicreji/deploiementlocal/scripts
    - test -s testUser

  when: on_success

failUserAdd:
  stage: failUserAdd
  script:
    - echo "Echec du test d'ajout d'un utilisateur"
  when: on_failure

successUserAdd:
  stage: successUserAdd
  script:
    - echo "Réussite du test d'ajout d'un utilisateur"
  when: on_success








